# SPDX-FileCopyrightText: Christoph Komanns, Florian Maurer
#
# SPDX-License-Identifier: MIT

repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.1.1
    hooks:
      - id: reuse
        args: ["annotate", "--license", "MIT", "--recursive", "--copyright", "NOWUM Developers", "--exclude-year", "--skip-unrecognised", "--skip-existing", "."]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.13.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-illegal-windows-names
